
import java.awt.Graphics;
import java.awt.Point;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author invitado
 */
public class Principal extends javax.swing.JFrame {
    Graphics gpsMiDibujo;
    int contador = 0;
    int x = 0;
    int xPrimera = 0;
    int y = 0;   
    int yPrimera = 0;
    int casoAlumProf = 1; //CASO 0 ES EL DE POINT, CASO 1 ES EL DEL ALUMNO USANDO CONTADOR
    Point coord= null;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        gpsMiDibujo = cnvDibujo.getGraphics();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cnvDibujo = new java.awt.Canvas();
        btnDetener = new javax.swing.JButton();
        btnUnirPuntos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setMinimumSize(new java.awt.Dimension(674, 342));

        cnvDibujo.setBackground(new java.awt.Color(204, 204, 204));
        cnvDibujo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cnvDibujoMouseClicked(evt);
            }
        });

        btnDetener.setText("Detener");
        btnDetener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetenerActionPerformed(evt);
            }
        });

        btnUnirPuntos.setText("Puntos");
        btnUnirPuntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnirPuntosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cnvDibujo, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDetener, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUnirPuntos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cnvDibujo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDetener)
                .addGap(18, 18, 18)
                .addComponent(btnUnirPuntos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cnvDibujoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cnvDibujoMouseClicked
          
   gpsMiDibujo.drawOval(evt.getX()-2, evt.getY()-2, 4, 4); 
   switch(casoAlumProf){
   case (0):
   if(coord != null){
       gpsMiDibujo.drawLine(coord.x, coord.y, evt.getX(), evt.getY());
       coord.x = evt.getX();
       coord.y = evt.getY();
       
   }else{
       coord = new Point (evt.getX(),evt.getY());
   }
   break;
   
   case (1):
       if(contador == 0){
       x = evt.getX();
       y = evt.getY();
       xPrimera = x;
       yPrimera = y;
       contador++;
   }else{
       gpsMiDibujo.drawOval(evt.getX()-2, evt.getY()-2, 4, 4);
       gpsMiDibujo.drawLine(x, y, evt.getX(), evt.getY());
       x = evt.getX();
       y = evt.getY();
       contador++;
   }
   break;
   }
       
    }//GEN-LAST:event_cnvDibujoMouseClicked

    private void btnDetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetenerActionPerformed
       contador = 0;
    }//GEN-LAST:event_btnDetenerActionPerformed

    private void btnUnirPuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnirPuntosActionPerformed
        if (contador > 2){
            gpsMiDibujo.drawLine(x, y, xPrimera, yPrimera);
            contador = 0;
        }
    }//GEN-LAST:event_btnUnirPuntosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetener;
    private javax.swing.JButton btnUnirPuntos;
    private java.awt.Canvas cnvDibujo;
    // End of variables declaration//GEN-END:variables
}
